<?php
session_start();
require('fpdf/fpdf.php');
include('connection.php');

// Check if supplier is logged in
if (!isset($_SESSION['supplier_id'])) {
    header("Location: supplierLogin.php");
    exit();
}

$supplier_id = $_SESSION['supplier_id'];

// Get supplier details
$supplier_query = "SELECT business_name FROM suppliers WHERE supplier_id = ?";
$stmt = $conn->prepare($supplier_query);
$stmt->bind_param("i", $supplier_id);
$stmt->execute();
$supplier_result = $stmt->get_result();
$supplier = $supplier_result->fetch_assoc();

// Get detailed order information
$orders_query = "SELECT o.id as order_id, o.user_id, o.amount, o.status, o.created_at, 
                        c.username as customer_name, c.email, c.phone_personal as phone,
                        GROUP_CONCAT(p.name) as products,
                        GROUP_CONCAT(oi.quantity) as quantities
                 FROM orders o
                 JOIN customers c ON o.user_id = c.id
                 JOIN order_items oi ON o.id = oi.order_id
                 JOIN product p ON oi.product_id = p.product_id
                 GROUP BY o.id
                 ORDER BY o.created_at DESC";

$orders_result = $conn->query($orders_query);
$orders = $orders_result->fetch_all(MYSQLI_ASSOC);

// Create new PDF document
$pdf = new FPDF();
$pdf->AddPage();

// Set font
$pdf->SetFont('Arial', 'B', 16);

// Title
$pdf->Cell(0, 10, 'CeylonCart Orders Report', 0, 1, 'C');
$pdf->Ln(5);

// Supplier name and report date
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 10, 'Supplier: ' . $supplier['business_name'], 0, 1);
$pdf->Cell(0, 10, 'Report Date: ' . date('Y-m-d H:i:s'), 0, 1);
$pdf->Ln(10);

// Total Orders Summary
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Total Orders: ' . count($orders), 0, 1);
$pdf->Ln(5);

// Orders Table Header
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(20, 10, 'Order ID', 1, 0, 'C');
$pdf->Cell(30, 10, 'Date', 1, 0, 'C');
$pdf->Cell(40, 10, 'Customer', 1, 0, 'C');
$pdf->Cell(40, 10, 'Products', 1, 0, 'C');
$pdf->Cell(20, 10, 'Quantity', 1, 0, 'C');
$pdf->Cell(30, 10, 'Amount', 1, 0, 'C');
$pdf->Cell(20, 10, 'Status', 1, 1, 'C');

// Orders Table Content
$pdf->SetFont('Arial', '', 10);
foreach ($orders as $order) {
    $products = explode(',', $order['products']);
    $quantities = explode(',', $order['quantities']);
    
    // First row with order details
    $pdf->Cell(20, 10, $order['order_id'], 1, 0, 'C');
    $pdf->Cell(30, 10, date('Y-m-d', strtotime($order['created_at'])), 1, 0, 'C');
    $pdf->Cell(40, 10, $order['customer_name'], 1, 0, 'C');
    $pdf->Cell(40, 10, $products[0], 1, 0, 'C');
    $pdf->Cell(20, 10, $quantities[0], 1, 0, 'C');
    $pdf->Cell(30, 10, '$' . number_format($order['amount'], 2), 1, 0, 'C');
    $pdf->Cell(20, 10, $order['status'], 1, 1, 'C');
    
    // Additional rows for multiple products
    for ($i = 1; $i < count($products); $i++) {
        $pdf->Cell(20, 10, '', 1, 0, 'C');
        $pdf->Cell(30, 10, '', 1, 0, 'C');
        $pdf->Cell(40, 10, '', 1, 0, 'C');
        $pdf->Cell(40, 10, $products[$i], 1, 0, 'C');
        $pdf->Cell(20, 10, $quantities[$i], 1, 0, 'C');
        $pdf->Cell(30, 10, '', 1, 0, 'C');
        $pdf->Cell(20, 10, '', 1, 1, 'C');
    }
}

$pdf->Ln(10);

// Add a footer
$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(0, 10, 'Generated by CeylonCart Supplier Dashboard', 0, 1, 'C');

// Output the PDF directly to the browser
$pdf->Output('I', 'orders_report_' . date('Y-m-d') . '.pdf');
?> 